"""Initial structure

Revision ID: 01
Revises: 
Create Date: 2025-12-27 23:25:05.084521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('location', sa.String(length=1024), nullable=False, comment='Относительный путь к изображению'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_index(op.f('ix_photos_is_active'), 'photos', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Имя пользователя'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='Телефон'),
    sa.Column('tg_id', sa.String(length=50), nullable=True, comment='Telegram ID'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хеш пароля'),
    sa.Column('role', sa.Integer(), nullable=False, comment='Роль пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint('char_length(email) >= 5', name='email_min_length'),
    sa.CheckConstraint('char_length(password_hash) >= 4', name='password_hash_min_length'),
    sa.CheckConstraint('char_length(phone) >= 12', name='phone_min_length'),
    sa.CheckConstraint('char_length(tg_id) >= 1', name='tg_id_min_length'),
    sa.CheckConstraint('char_length(username) >= 3', name='username_min_length'),
    sa.CheckConstraint('role IN (0, 1, 2)', name='role_valid_values'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cafes',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название'),
    sa.Column('address', sa.String(length=256), nullable=False, comment='Адрес'),
    sa.Column('phone', sa.String(length=32), nullable=False, comment='Телефон'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('photo_id', sa.UUID(), nullable=True, comment='ID изображения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint("phone ~ '^\\+?[1-9]\\d{4,}$'", name='ck_cafe_phone_format'),
    sa.CheckConstraint('LENGTH(TRIM(phone)) >= 5', name='ck_cafe_phone_min_length'),
    sa.CheckConstraint('char_length(address) > 5', name='ck_cafe_address_min_length'),
    sa.CheckConstraint('char_length(name) > 2', name='ck_cafe_name_min_length'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafes_is_active'), 'cafes', ['is_active'], unique=False)
    op.create_index(op.f('ix_cafes_name'), 'cafes', ['name'], unique=False)
    op.create_table('dishes',
    sa.Column('name', sa.String(length=64), nullable=False, comment='Название'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('photo_id', sa.UUID(), nullable=True, comment='ID изображения'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint('price > 0', name='check_positive_price'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_is_active'), 'dishes', ['is_active'], unique=False)
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=False)
    op.create_index(op.f('ix_dishes_photo_id'), 'dishes', ['photo_id'], unique=False)
    op.create_table('bookings',
    sa.Column('cafe_id', sa.Integer(), nullable=False, comment='ID кафе'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('guest_number', sa.Integer(), nullable=False, comment='Количество гостей'),
    sa.Column('note', sa.Text(), nullable=True, comment='Заметка'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус бронирования'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='Дата бронирования'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint('guest_number > 0', name='check_guest_number_higher_then_0'),
    sa.CheckConstraint('status IN (0, 1, 2)', name='check_booking_status_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'booking_date', 'cafe_id', name='uq_user_date_cafe')
    )
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_cafe_id'), 'bookings', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_bookings_is_active'), 'bookings', ['is_active'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('cafe_managers',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cafe_id', 'user_id')
    )
    op.create_table('dish_cafes',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dish_id', 'cafe_id')
    )
    op.create_table('slots',
    sa.Column('start_time', sa.Time(), nullable=False, comment='Время начала слота'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Время окончания слота'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('cafe_id', sa.Integer(), nullable=False, comment='ID кафе'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint('end_time > start_time', name='check_end_time_after_start_time'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_cafe_id'), 'slots', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_slots_is_active'), 'slots', ['is_active'], unique=False)
    op.create_table('tables',
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('seat_number', sa.Integer(), nullable=False, comment='Количество посадочных мест'),
    sa.Column('cafe_id', sa.Integer(), nullable=False, comment='ID кафе'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Флаг активности записи'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.CheckConstraint('seat_number BETWEEN 1 AND 20', name='check_seat_number_positive_and_lt_max_seat_number'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_cafe_id'), 'tables', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_tables_is_active'), 'tables', ['is_active'], unique=False)
    op.create_table('bookingtableslots',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор (Integer)'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'table_id', 'slot_id', name='uq_booking_table_slot')
    )
    op.create_index(op.f('ix_bookingtableslots_booking_id'), 'bookingtableslots', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookingtableslots_slot_id'), 'bookingtableslots', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookingtableslots_table_id'), 'bookingtableslots', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookingtableslots_table_id'), table_name='bookingtableslots')
    op.drop_index(op.f('ix_bookingtableslots_slot_id'), table_name='bookingtableslots')
    op.drop_index(op.f('ix_bookingtableslots_booking_id'), table_name='bookingtableslots')
    op.drop_table('bookingtableslots')
    op.drop_index(op.f('ix_tables_is_active'), table_name='tables')
    op.drop_index(op.f('ix_tables_cafe_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_slots_is_active'), table_name='slots')
    op.drop_index(op.f('ix_slots_cafe_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_table('dish_cafes')
    op.drop_table('cafe_managers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_is_active'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cafe_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_dishes_photo_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_is_active'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_cafes_name'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_is_active'), table_name='cafes')
    op.drop_table('cafes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_photos_is_active'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
