# Общие ограничения для названий и адресов
NAME_MIN_LENGTH = 2
NAME_MAX_LENGTH = 200
ADDRESS_MIN_LENGTH = 5
ADDRESS_MAX_LENGTH = 256

# Ограничения для путей к файлам
PHOTO_PATH_MAX_LENGTH = 1024

# Ограничения для кафе
MAX_MANAGERS = 10
CAFE_MIN_SEAT_NUMBER = 1
CAFE_MAX_SEAT_NUMBER = 20
SLOT_MIN_DURATION_MINUTES = 30
DESCRIPTION_MIN_LENGTH = 5
DESCRIPTION_MAX_LENGTH = 200

# Ограничения для телефонов
PHONE_MIN_LENGTH = 12
PHONE_MAX_LENGTH = 32

# Ограничения для блюд
DISH_NAME_MIN_LENGTH = 2
DISH_NAME_MAX_LENGTH = 64

# Ограничения для пользователей
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 50
EMAIL_MIN_LENGTH = 5
EMAIL_MAX_LENGTH = 100
TG_ID_MIN_LENGTH = 1
TG_ID_MAX_LENGTH = 50
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 255
PASSWORD_HASH_MIN_LENGTH = 4

DEFAULT_QUERY_LIMIT = 100
MAX_QUERY_LIMIT = 1000
